### ISSUE TITLE
InputListの取得方法について

### ISSUE THREAD

**Issue by Preld** [naichilab/Unity-TouchManager#1]
TouchManagerのupdateメソッド内でtouchしているかに関わらず、InputListに値を格納しているのでFlick判定時にFlick中の時間が正確に測れていません。
e.ElapsedTimeという名前から察するにフリックにかかった時間を取得してると思ったのですが、実際はフリックとフリックの間の時間を取得しています。もしこれが意図した動作であるならば、TRACE_QUEUE_COUNTが20程度の値（60FPSならば0.3秒の値が常に出てくる、それ以上に高速にフリックすることなどまずない）だとまったく意味のない値を取得することになってしまいます。

**Comment by naichilab** [comment]
@Preld さん、ご指摘ありがとうございます。
仰る通り、今のフリック検出は全くもって実用に耐えません･･･。
その点は認識しておりまして、現在下記仕様にて修正中です。
1. 数フレーム前（フレーム数は設定可能）との座標の変化から速度を計算
2. 数フレーム前（フレーム数は設定可能）との速度の変化から加速度を計算
3. タップされており、加速度が閾値（設定可能）以上となった場合にフリック開始と判断
4. フリック中で速度が閾値（設定可能）以下となった場合、フリック中断と判断
5. フリック中に指が離れた場合に、フリックイベントを投げる。
    ※合わせて最大フリック時間、最短フリック距離などを設定できるようにします。

今夜～数日以内に公開できると思いますのでお待ちいただければ幸いです。

**Comment by naichilab** [comment]
フリック判定ロジックの刷新を行いました。
